formats: [htmlzip]
version: 2
python:
   version: 3.6
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
        path: openTCGA
   system_packages: true